openapi: 3.0.0
info:
  title: User Context API
  description: 'Retrieve details of users/contacts'
  version: 1.0.0
servers:
  - url: 'http://ifm.sodexo.com/api/v1/user'
paths:
  /:
    get:
      tags:
        - get user 
      summary: 'Return user details'
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
          description: email id of the user to retrieve
      responses:
        '200':
          description: 'user returned'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: user not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    User:
      type: object
      required:
        - email
      properties:
        fullName:
          type: string
        type:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        mobile:
          type: string
        contract:
          $ref: '#/components/schemas/Contract'
        site:
          $ref: '#/components/schemas/Site'
        location:
          $ref: '#/components/schemas/Location'      
        language:
          type: string
    Contract:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    Site:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
    Location:
      type: object
      properties:
        code:
          type: string
        level:
          type: integer
        parent:
          type: string
        description:
          type: string
        type:
          type: string
    ErrorResponse:
      type: object
      properties:
        Message:
          type: string
        ExceptionMessage:
          type: string        
        ExceptionType:
          type: string        
        Detail:
          type: string
